Validation ControlledVocabularies {
    {"ActiveAxes",{}},
    {"ActuatorState",{{"ACTIVE", 0}, {"INACTIVE", 0} }},
    {"Alarm",{}},
    {"AssetChanged",{}},
    {"AssetRemoved",{}},
    {"Availability",{{"AVAILABLE", 0}, {"UNAVAILABLE", 0} }},
    {"AxisCoupling",{{"MASTER", 0}, {"SLAVE", 0}, {"SYNCHRONOUS", 0}, {"TANDEM", 0} }},
    {"AxisFeedrateOverride",{}},
    {"AxisInterlock",{{"ACTIVE", 0}, {"INACTIVE", 0} }},
    {"AxisState",{{"HOME", 0}, {"PARKED", 0}, {"STOPPED", 0}, {"TRAVEL", 0} }},
    {"Block",{}},
    {"BlockCount",{}},
    {"ChuckInterlock",{{"ACTIVE", 0}, {"INACTIVE", 0} }},
    {"ChuckState",{{"CLOSED", 0}, {"OPEN", 0}, {"UNLATCHED", 0} }},
    {"Code",{}},
    {"CompositionState",{}},
    {"ControllerMode",{{"AUTOMATIC", 0}, {"MANUAL", 0}, {"MANUAL_DATA_INPUT", 0}, {"SEMI_AUTOMATIC", 0}, {"FEED_HOLD", SCHEMA_VERSION(1, 3)}, {"EDIT", 0} }},
    {"ControllerModeOverride",{{"OFF", 0}, {"ON", 0} }},
    {"CoupledAxes",{}},
    {"DateCode",{}},
    {"DeviceUuid",{}},
    {"Direction",{{"CLOCKWISE", SCHEMA_VERSION(1, 4)}, {"COUNTER_CLOCKWISE", SCHEMA_VERSION(1, 4)}, {"NEGATIVE", SCHEMA_VERSION(1, 4)}, {"POSITIVE", SCHEMA_VERSION(1, 4)} }},
    {"DoorState",{{"CLOSED", 0}, {"OPEN", 0}, {"UNLATCHED", 0} }},
    {"EmergencyStop",{{"ARMED", 0}, {"TRIGGERED", 0} }},
    {"EndOfBar",{{"NO", 0}, {"YES", 0} }},
    {"EquipmentMode",{{"OFF", 0}, {"ON", 0} }},
    {"Execution",{{"ACTIVE", 0}, {"INTERRUPTED", 0}, {"READY", 0}, {"STOPPED", 0}, {"FEED_HOLD", 0}, {"PROGRAM_COMPLETED", 0}, {"PROGRAM_OPTIONAL_STOP", SCHEMA_VERSION(1, 4)}, {"PROGRAM_STOPPED", 0}, {"OPTIONAL_STOP", 0}, {"WAIT", 0} }},
    {"FunctionalMode",{{"MAINTENANCE", 0}, {"PROCESS_DEVELOPMENT", 0}, {"PRODUCTION", 0}, {"SETUP", 0}, {"TEARDOWN", 0} }},
    {"Hardness",{}},
    {"Line",{}},
    {"LineLabel",{}},
    {"LineNumber",{}},
    {"Material",{}},
    {"MaterialLayer",{}},
    {"Message",{}},
    {"OperatorId",{}},
    {"PalletId",{}},
    {"PartCount",{}},
    {"PartDetect",{{"NOT_PRESENT", 0}, {"PRESENT", 0} }},
    {"PartId",{}},
    {"PartNumber",{}},
    {"PathFeedrateOverride",{}},
    {"PathMode",{{"INDEPENDENT", 0}, {"MIRROR", 0}, {"SYNCHRONOUS", 0}, {"MASTER", 0} }},
    {"PowerState",{{"OFF", 0}, {"ON", 0} }},
    {"PowerStatus",{{"OFF", SCHEMA_VERSION(1, 1)}, {"ON", SCHEMA_VERSION(1, 1)} }},
    {"ProcessTime",{}},
    {"Program",{}},
    {"ProgramComment",{}},
    {"ProgramEdit",{{"ACTIVE", 0}, {"NOT_READY", 0}, {"READY", 0} }},
    {"ProgramEditName",{}},
    {"ProgramHeader",{}},
    {"ProgramLocation",{}},
    {"ProgramLocationType",{{"EXTERNAL", 0}, {"LOCAL", 0} }},
    {"ProgramNestLevel",{}},
    {"RotaryMode",{{"CONTOUR", 0}, {"INDEX", 0}, {"SPINDLE", 0} }},
    {"RotaryVelocityOverride",{}},
    {"SerialNumber",{}},
    {"SpindleInterlock",{{"ACTIVE", 0}, {"INACTIVE", 0} }},
    {"ToolAssetId",{}},
    {"ToolGroup",{}},
    {"ToolId",{}},
    {"ToolNumber",{}},
    {"ToolOffset",{}},
    {"User",{}},
    {"Variable",{}},
    {"WaitState",{{"MATERIAL_LOAD", 0}, {"MATERIAL_UNLOAD", 0}, {"PART_LOAD", 0}, {"PART_UNLOAD", 0}, {"PAUSING", 0}, {"POWERING_DOWN", 0}, {"POWERING_UP", 0}, {"RESUMING", 0}, {"SECONDARY_PROCESS", 0}, {"TOOL_LOAD", 0}, {"TOOL_UNLOAD", 0} }},
    {"Wire",{}},
    {"WorkholdingId",{}},
    {"WorkOffset",{}},
    {"OperatingSystem",{}},
    {"Firmware",{}},
    {"Application",{}},
    {"Library",{}},
    {"Hardware",{}},
    {"Network",{}},
    {"Rotation",{}},
    {"Translation",{}},
    {"ProcessKindId",{}},
    {"PartStatus",{{"FAIL", 0}, {"PASS", 0} }},
    {"AlarmLimit",{}},
    {"ProcessAggregateId",{}},
    {"PartKindId",{}},
    {"AdapterURI",{}},
    {"DeviceRemoved",{}},
    {"DeviceChanged",{}},
    {"SpecificationLimit",{}},
    {"ConnectionStatus",{{"CLOSED", 0}, {"ESTABLISHED", 0}, {"LISTEN", 0} }},
    {"AdapterSoftwareVersion",{}},
    {"SensorAttachment",{}},
    {"ControlLimit",{}},
    {"DeviceAdded",{}},
    {"MTConnectVersion",{}},
    {"ProcessOccurrenceId",{}},
    {"PartGroupId",{}},
    {"PartUniqueId",{}},
    {"ActivationCount",{}},
    {"DeactivationCount",{}},
    {"TransferCount",{}},
    {"LoadCount",{}},
    {"PartProcessingState",{{"IN_PROCESS", 0}, {"IN_TRANSIT", 0}, {"NEEDS_PROCESSING", 0}, {"PROCESSING_ENDED", 0}, {"PROCESSING_ENDED_ABORTED", 0}, {"PROCESSING_ENDED_COMPLETE", 0}, {"PROCESSING_ENDED_LOST", 0}, {"PROCESSING_ENDED_REJECTED", 0}, {"PROCESSING_ENDED_SKIPPED", 0}, {"PROCESSING_ENDED_STOPPED", 0}, {"TRANSIT_COMPLETE", 0}, {"WAITING_FOR_TRANSIT", 0} }},
    {"ProcessState",{{"ABORTED", 0}, {"ACTIVE", 0}, {"COMPLETE", 0}, {"INITIALIZING", 0}, {"INTERRUPTED", 0}, {"READY", 0} }},
    {"ValveState",{{"CLOSED", 0}, {"CLOSING", 0}, {"OPEN", 0}, {"OPENING", 0} }},
    {"LockState",{{"LOCKED", 0}, {"UNLOCKED", 0} }},
    {"UnloadCount",{}},
    {"CycleCount",{}},
    {"OperatingMode",{{"AUTOMATIC", 0}, {"MANUAL", 0}, {"SEMI_AUTOMATIC", 0} }},
    {"AssetCount",{}},
    {"MaintenanceList",{}},
    {"FixtureId",{}},
    {"PartCountType",{{"BATCH", 0}, {"EACH", 0} }},
    {"ClockTime",{}},
    {"NetworkPort",{}},
    {"HostName",{}},
    {"LeakDetect",{{"DETECTED", 0}, {"NOT_DETECTED", 0} }},
    {"BatteryState",{{"CHARGED", 0}, {"CHARGING", 0}, {"DISCHARGED", 0}, {"DISCHARGING", 0} }},
    {"FeaturePersisitentId",{}},
    {"SensorState",{}},
    {"ComponentData",{}},
    {"WorkOffsets",{}},
    {"ToolOffsets",{}},
    {"FeatureMeasurement",{}},
    {"CharacteristicPersistentId",{}},
    {"MeasurementType",{}},
    {"MeasurementValue",{}},
    {"MeasurementUnits",{}},
    {"CharacteristicStatus",{{"BASIC_OR_THEORETIC_EXACT_DIMENSION", 0}, {"FAIL", 0}, {"INDETERMINATE", 0}, {"NOT_ANALYZED", 0}, {"PASS", 0}, {"REWORK", 0}, {"SYSTEM_ERROR", 0}, {"UNDEFINED", 0} }},
    {"UncertaintyType",{{"COMBINED", 0}, {"MEAN", 0} }},
    {"Uncertainty",{}},
    {"AlarmLimits",{}},
    {"ControlLimits",{}},
    {"SpecificationLimits",{}},
    {"ToolCuttingItem",{}},
    {"LocationAddress",{}},
    {"ActivePowerSource",{}},
    {"LocationNarrative",{}},
    {"Thickness",{}},
    {"LocationSpatialGeographic",{}}
};