Validation ControlledVocabularies {
    {"ActiveAxes", {}},
    {"ActuatorState",
     {{"ACTIVE", {SCHEMA_VERSION(1, 2), 0}}, {"INACTIVE", {SCHEMA_VERSION(1, 2), 0}}}},
    {"Alarm", {}},
    {"AssetChanged", {}},
    {"AssetRemoved", {}},
    {"Availability",
     {{"AVAILABLE", {SCHEMA_VERSION(1, 1), 0}}, {"UNAVAILABLE", {SCHEMA_VERSION(1, 1), 0}}}},
    {"AxisCoupling",
     {{"MASTER", {SCHEMA_VERSION(1, 1), 0}},
      {"SLAVE", {SCHEMA_VERSION(1, 1), 0}},
      {"SYNCHRONOUS", {SCHEMA_VERSION(1, 1), 0}},
      {"TANDEM", {SCHEMA_VERSION(1, 1), 0}}}},
    {"AxisFeedrateOverride", {}},
    {"AxisInterlock",
     {{"ACTIVE", {SCHEMA_VERSION(1, 3), 0}}, {"INACTIVE", {SCHEMA_VERSION(1, 3), 0}}}},
    {"AxisState",
     {{"HOME", {SCHEMA_VERSION(1, 3), 0}},
      {"PARKED", {SCHEMA_VERSION(1, 3), 0}},
      {"STOPPED", {SCHEMA_VERSION(1, 3), 0}},
      {"TRAVEL", {SCHEMA_VERSION(1, 3), 0}}}},
    {"Block", {}},
    {"BlockCount", {}},
    {"ChuckInterlock",
     {{"ACTIVE", {SCHEMA_VERSION(1, 3), 0}}, {"INACTIVE", {SCHEMA_VERSION(1, 3), 0}}}},
    {"ChuckState",
     {{"CLOSED", {SCHEMA_VERSION(1, 3), 0}},
      {"OPEN", {SCHEMA_VERSION(1, 3), 0}},
      {"UNLATCHED", {SCHEMA_VERSION(1, 3), 0}}}},
    {"Code", {}},
    {"CompositionState", {}},
    {"ControllerMode",
     {{"AUTOMATIC", {SCHEMA_VERSION(1, 0), 0}},
      {"MANUAL", {SCHEMA_VERSION(1, 0), 0}},
      {"MANUAL_DATA_INPUT", {SCHEMA_VERSION(1, 0), 0}},
      {"SEMI_AUTOMATIC", {SCHEMA_VERSION(1, 1), 0}},
      {"FEED_HOLD", {SCHEMA_VERSION(1, 2), SCHEMA_VERSION(1, 3)}},
      {"EDIT", {SCHEMA_VERSION(1, 3), 0}}}},
    {"ControllerModeOverride",
     {{"OFF", {SCHEMA_VERSION(1, 4), 0}}, {"ON", {SCHEMA_VERSION(1, 4), 0}}}},
    {"CoupledAxes", {}},
    {"DateCode", {}},
    {"DeviceUuid", {}},
    {"Direction",
     {{"CLOCKWISE", {SCHEMA_VERSION(1, 0), SCHEMA_VERSION(1, 4)}},
      {"COUNTER_CLOCKWISE", {SCHEMA_VERSION(1, 0), SCHEMA_VERSION(1, 4)}},
      {"NEGATIVE", {SCHEMA_VERSION(1, 2), SCHEMA_VERSION(1, 4)}},
      {"POSITIVE", {SCHEMA_VERSION(1, 2), SCHEMA_VERSION(1, 4)}}}},
    {"DoorState",
     {{"CLOSED", {SCHEMA_VERSION(1, 1), 0}},
      {"OPEN", {SCHEMA_VERSION(1, 1), 0}},
      {"UNLATCHED", {SCHEMA_VERSION(1, 2), 0}}}},
    {"EmergencyStop",
     {{"ARMED", {SCHEMA_VERSION(1, 1), 0}}, {"TRIGGERED", {SCHEMA_VERSION(1, 1), 0}}}},
    {"EndOfBar", {{"NO", {SCHEMA_VERSION(1, 3), 0}}, {"YES", {SCHEMA_VERSION(1, 3), 0}}}},
    {"EquipmentMode", {{"OFF", {SCHEMA_VERSION(1, 4), 0}}, {"ON", {SCHEMA_VERSION(1, 4), 0}}}},
    {"Execution",
     {{"ACTIVE", {SCHEMA_VERSION(1, 0), 0}},
      {"INTERRUPTED", {SCHEMA_VERSION(1, 0), 0}},
      {"READY", {SCHEMA_VERSION(1, 0), 0}},
      {"STOPPED", {SCHEMA_VERSION(1, 0), 0}},
      {"FEED_HOLD", {SCHEMA_VERSION(1, 3), 0}},
      {"PROGRAM_COMPLETED", {SCHEMA_VERSION(1, 3), 0}},
      {"PROGRAM_OPTIONAL_STOP", {SCHEMA_VERSION(1, 3), SCHEMA_VERSION(1, 4)}},
      {"PROGRAM_STOPPED", {SCHEMA_VERSION(1, 3), 0}},
      {"OPTIONAL_STOP", {SCHEMA_VERSION(1, 4), 0}},
      {"WAIT", {SCHEMA_VERSION(1, 5), 0}}}},
    {"FunctionalMode",
     {{"MAINTENANCE", {SCHEMA_VERSION(1, 3), 0}},
      {"PROCESS_DEVELOPMENT", {SCHEMA_VERSION(1, 3), 0}},
      {"PRODUCTION", {SCHEMA_VERSION(1, 3), 0}},
      {"SETUP", {SCHEMA_VERSION(1, 3), 0}},
      {"TEARDOWN", {SCHEMA_VERSION(1, 3), 0}}}},
    {"Hardness", {}},
    {"Line", {}},
    {"LineLabel", {}},
    {"LineNumber", {}},
    {"Material", {}},
    {"MaterialLayer", {}},
    {"Message", {}},
    {"OperatorId", {}},
    {"PalletId", {}},
    {"PartCount", {}},
    {"PartDetect",
     {{"NOT_PRESENT", {SCHEMA_VERSION(1, 5), 0}}, {"PRESENT", {SCHEMA_VERSION(1, 5), 0}}}},
    {"PartId", {}},
    {"PartNumber", {}},
    {"PathFeedrateOverride", {}},
    {"PathMode",
     {{"INDEPENDENT", {SCHEMA_VERSION(1, 1), 0}},
      {"MIRROR", {SCHEMA_VERSION(1, 1), 0}},
      {"SYNCHRONOUS", {SCHEMA_VERSION(1, 1), 0}},
      {"MASTER", {SCHEMA_VERSION(1, 2), 0}}}},
    {"PowerState", {{"OFF", {SCHEMA_VERSION(1, 1), 0}}, {"ON", {SCHEMA_VERSION(1, 1), 0}}}},
    {"PowerStatus",
     {{"OFF", {SCHEMA_VERSION(1, 0), SCHEMA_VERSION(1, 1)}},
      {"ON", {SCHEMA_VERSION(1, 0), SCHEMA_VERSION(1, 1)}}}},
    {"ProcessTime", {}},
    {"Program", {}},
    {"ProgramComment", {}},
    {"ProgramEdit",
     {{"ACTIVE", {SCHEMA_VERSION(1, 3), 0}},
      {"NOT_READY", {SCHEMA_VERSION(1, 3), 0}},
      {"READY", {SCHEMA_VERSION(1, 3), 0}}}},
    {"ProgramEditName", {}},
    {"ProgramHeader", {}},
    {"ProgramLocation", {}},
    {"ProgramLocationType",
     {{"EXTERNAL", {SCHEMA_VERSION(1, 5), 0}}, {"LOCAL", {SCHEMA_VERSION(1, 5), 0}}}},
    {"ProgramNestLevel", {}},
    {"RotaryMode",
     {{"CONTOUR", {SCHEMA_VERSION(1, 1), 0}},
      {"INDEX", {SCHEMA_VERSION(1, 1), 0}},
      {"SPINDLE", {SCHEMA_VERSION(1, 1), 0}}}},
    {"RotaryVelocityOverride", {}},
    {"SerialNumber", {}},
    {"SpindleInterlock",
     {{"ACTIVE", {SCHEMA_VERSION(1, 3), 0}}, {"INACTIVE", {SCHEMA_VERSION(1, 3), 0}}}},
    {"ToolAssetId", {}},
    {"ToolGroup", {}},
    {"ToolId", {}},
    {"ToolNumber", {}},
    {"ToolOffset", {}},
    {"User", {}},
    {"Variable", {}},
    {"WaitState",
     {{"MATERIAL_LOAD", {SCHEMA_VERSION(1, 5), 0}},
      {"MATERIAL_UNLOAD", {SCHEMA_VERSION(1, 5), 0}},
      {"PART_LOAD", {SCHEMA_VERSION(1, 5), 0}},
      {"PART_UNLOAD", {SCHEMA_VERSION(1, 5), 0}},
      {"PAUSING", {SCHEMA_VERSION(1, 5), 0}},
      {"POWERING_DOWN", {SCHEMA_VERSION(1, 5), 0}},
      {"POWERING_UP", {SCHEMA_VERSION(1, 5), 0}},
      {"RESUMING", {SCHEMA_VERSION(1, 5), 0}},
      {"SECONDARY_PROCESS", {SCHEMA_VERSION(1, 5), 0}},
      {"TOOL_LOAD", {SCHEMA_VERSION(1, 5), 0}},
      {"TOOL_UNLOAD", {SCHEMA_VERSION(1, 5), 0}}}},
    {"Wire", {}},
    {"WorkholdingId", {}},
    {"WorkOffset", {}},
    {"OperatingSystem", {}},
    {"Firmware", {}},
    {"Application", {}},
    {"Library", {}},
    {"Hardware", {}},
    {"Network", {}},
    {"Rotation", {}},
    {"Translation", {}},
    {"ProcessKindId", {}},
    {"PartStatus", {{"FAIL", {SCHEMA_VERSION(1, 7), 0}}, {"PASS", {SCHEMA_VERSION(1, 7), 0}}}},
    {"AlarmLimit", {}},
    {"ProcessAggregateId", {}},
    {"PartKindId", {}},
    {"AdapterURI", {}},
    {"DeviceRemoved", {}},
    {"DeviceChanged", {}},
    {"SpecificationLimit", {}},
    {"ConnectionStatus",
     {{"CLOSED", {SCHEMA_VERSION(1, 7), 0}},
      {"ESTABLISHED", {SCHEMA_VERSION(1, 7), 0}},
      {"LISTEN", {SCHEMA_VERSION(1, 7), 0}}}},
    {"AdapterSoftwareVersion", {}},
    {"SensorAttachment", {}},
    {"ControlLimit", {}},
    {"DeviceAdded", {}},
    {"MTConnectVersion", {}},
    {"ProcessOccurrenceId", {}},
    {"PartGroupId", {}},
    {"PartUniqueId", {}},
    {"ActivationCount", {}},
    {"DeactivationCount", {}},
    {"TransferCount", {}},
    {"LoadCount", {}},
    {"PartProcessingState",
     {{"IN_PROCESS", {SCHEMA_VERSION(1, 8), 0}},
      {"IN_TRANSIT", {SCHEMA_VERSION(1, 8), 0}},
      {"NEEDS_PROCESSING", {SCHEMA_VERSION(1, 8), 0}},
      {"PROCESSING_ENDED", {SCHEMA_VERSION(1, 8), 0}},
      {"PROCESSING_ENDED_ABORTED", {SCHEMA_VERSION(1, 8), 0}},
      {"PROCESSING_ENDED_COMPLETE", {SCHEMA_VERSION(1, 8), 0}},
      {"PROCESSING_ENDED_LOST", {SCHEMA_VERSION(1, 8), 0}},
      {"PROCESSING_ENDED_REJECTED", {SCHEMA_VERSION(1, 8), 0}},
      {"PROCESSING_ENDED_SKIPPED", {SCHEMA_VERSION(1, 8), 0}},
      {"PROCESSING_ENDED_STOPPED", {SCHEMA_VERSION(1, 8), 0}},
      {"TRANSIT_COMPLETE", {SCHEMA_VERSION(1, 8), 0}},
      {"WAITING_FOR_TRANSIT", {SCHEMA_VERSION(1, 8), 0}}}},
    {"ProcessState",
     {{"ABORTED", {SCHEMA_VERSION(1, 8), 0}},
      {"ACTIVE", {SCHEMA_VERSION(1, 8), 0}},
      {"COMPLETE", {SCHEMA_VERSION(1, 8), 0}},
      {"INITIALIZING", {SCHEMA_VERSION(1, 8), 0}},
      {"INTERRUPTED", {SCHEMA_VERSION(1, 8), 0}},
      {"READY", {SCHEMA_VERSION(1, 8), 0}}}},
    {"ValveState",
     {{"CLOSED", {SCHEMA_VERSION(1, 8), 0}},
      {"CLOSING", {SCHEMA_VERSION(1, 8), 0}},
      {"OPEN", {SCHEMA_VERSION(1, 8), 0}},
      {"OPENING", {SCHEMA_VERSION(1, 8), 0}}}},
    {"LockState", {{"LOCKED", {SCHEMA_VERSION(1, 8), 0}}, {"UNLOCKED", {SCHEMA_VERSION(1, 8), 0}}}},
    {"UnloadCount", {}},
    {"CycleCount", {}},
    {"OperatingMode",
     {{"AUTOMATIC", {SCHEMA_VERSION(2, 0), 0}},
      {"MANUAL", {SCHEMA_VERSION(2, 0), 0}},
      {"SEMI_AUTOMATIC", {SCHEMA_VERSION(2, 0), 0}}}},
    {"AssetCount", {}},
    {"MaintenanceList", {}},
    {"FixtureId", {}},
    {"PartCountType", {{"BATCH", {SCHEMA_VERSION(2, 0), 0}}, {"EACH", {SCHEMA_VERSION(2, 0), 0}}}},
    {"ClockTime", {}},
    {"NetworkPort", {}},
    {"HostName", {}},
    {"LeakDetect",
     {{"DETECTED", {SCHEMA_VERSION(2, 1), 0}}, {"NOT_DETECTED", {SCHEMA_VERSION(2, 1), 0}}}},
    {"BatteryState",
     {{"CHARGED", {SCHEMA_VERSION(2, 1), 0}},
      {"CHARGING", {SCHEMA_VERSION(2, 1), 0}},
      {"DISCHARGED", {SCHEMA_VERSION(2, 1), 0}},
      {"DISCHARGING", {SCHEMA_VERSION(2, 1), 0}}}},
    {"FeaturePersisitentId", {}},
    {"SensorState", {}},
    {"ComponentData", {}},
    {"WorkOffsets", {}},
    {"ToolOffsets", {}},
    {"FeatureMeasurement", {}},
    {"CharacteristicPersistentId", {}},
    {"MeasurementType", {}},
    {"MeasurementValue", {}},
    {"MeasurementUnits", {}},
    {"CharacteristicStatus",
     {{"BASIC_OR_THEORETIC_EXACT_DIMENSION", {SCHEMA_VERSION(2, 2), 0}},
      {"FAIL", {SCHEMA_VERSION(2, 2), 0}},
      {"INDETERMINATE", {SCHEMA_VERSION(2, 2), 0}},
      {"NOT_ANALYZED", {SCHEMA_VERSION(2, 2), 0}},
      {"PASS", {SCHEMA_VERSION(2, 2), 0}},
      {"REWORK", {SCHEMA_VERSION(2, 2), 0}},
      {"SYSTEM_ERROR", {SCHEMA_VERSION(2, 2), 0}},
      {"UNDEFINED", {SCHEMA_VERSION(2, 2), 0}}}},
    {"UncertaintyType",
     {{"COMBINED", {SCHEMA_VERSION(2, 2), 0}}, {"MEAN", {SCHEMA_VERSION(2, 2), 0}}}},
    {"Uncertainty", {}},
    {"AlarmLimits", {}},
    {"ControlLimits", {}},
    {"SpecificationLimits", {}},
    {"ToolCuttingItem", {}},
    {"LocationAddress", {}},
    {"ActivePowerSource", {}},
    {"LocationNarrative", {}},
    {"Thickness", {}},
    {"LocationSpatialGeographic", {}}};