const Validation ControlledVocabularies {
    {"ACTIVE_AXES", {}},
    {"ACTUATOR_STATE", {{"ACTIVE", 0}, {"INACTIVE", 0}}},
    {"ALARM", {}},
    {"ASSET_CHANGED", {}},
    {"ASSET_REMOVED", {}},
    {"AVAILABILITY", {{"AVAILABLE", 0}, {"UNAVAILABLE", 0}}},
    {"AXIS_COUPLING", {{"TANDEM", 0}, {"SYNCHRONOUS", 0}, {"MASTER", 0}, {"SLAVE", 0}}},
    {"AXIS_FEEDRATE_OVERRIDE", {}},
    {"AXIS_INTERLOCK", {{"ACTIVE", 0}, {"INACTIVE", 0}}},
    {"AXIS_STATE", {{"HOME", 0}, {"TRAVEL", 0}, {"PARKED", 0}, {"STOPPED", 0}}},
    {"BLOCK", {}},
    {"BLOCK_COUNT", {}},
    {"CHUCK_INTERLOCK", {{"ACTIVE", 0}, {"INACTIVE", 0}}},
    {"CHUCK_STATE", {{"OPEN", 0}, {"CLOSED", 0}, {"UNLATCHED", 0}}},
    {"CODE", {}},
    {"COMPOSITION_STATE", {}},
    {"CONTROLLER_MODE", {{"AUTOMATIC", 0}, {"MANUAL", 0}, {"MANUAL_DATA_INPUT", 0}, {"SEMI_AUTOMATIC", 0}, {"EDIT", 0}, {"FEED_HOLD", SCHEMA_VERSION(1, 3)}}},
    {"CONTROLLER_MODE_OVERRIDE", {{"ON", 0}, {"OFF", 0}}},
    {"COUPLED_AXES", {}},
    {"DATE_CODE", {}},
    {"DEVICE_UUID", {}},
    {"DIRECTION", {{"CLOCKWISE", SCHEMA_VERSION(1, 4)}, {"COUNTER_CLOCKWISE", SCHEMA_VERSION(1, 4)}, {"POSITIVE", SCHEMA_VERSION(1, 4)}, {"NEGATIVE", SCHEMA_VERSION(1, 4)}}},
    {"DOOR_STATE", {{"OPEN", 0}, {"CLOSED", 0}, {"UNLATCHED", 0}}},
    {"EMERGENCY_STOP", {{"ARMED", 0}, {"TRIGGERED", 0}}},
    {"END_OF_BAR", {{"YES", 0}, {"NO", 0}}},
    {"EQUIPMENT_MODE", {{"ON", 0}, {"OFF", 0}}},
    {"EXECUTION", {{"READY", 0}, {"ACTIVE", 0}, {"INTERRUPTED", 0}, {"FEED_HOLD", 0}, {"STOPPED", 0}, {"OPTIONAL_STOP", 0}, {"PROGRAM_STOPPED", 0}, {"PROGRAM_COMPLETED", 0}, {"WAIT", 0}, {"PROGRAM_OPTIONAL_STOP", SCHEMA_VERSION(1, 4)}}},
    {"FUNCTIONAL_MODE", {{"PRODUCTION", 0}, {"SETUP", 0}, {"TEARDOWN", 0}, {"MAINTENANCE", 0}, {"PROCESS_DEVELOPMENT", 0}}},
    {"HARDNESS", {}},
    {"LINE", {}},
    {"LINE_LABEL", {}},
    {"LINE_NUMBER", {}},
    {"MATERIAL", {}},
    {"MATERIAL_LAYER", {}},
    {"MESSAGE", {}},
    {"OPERATOR_ID", {}},
    {"PALLET_ID", {}},
    {"PART_COUNT", {}},
    {"PART_DETECT", {{"PRESENT", 0}, {"NOT_PRESENT", 0}}},
    {"PART_ID", {}},
    {"PART_NUMBER", {}},
    {"PATH_FEEDRATE_OVERRIDE", {}},
    {"PATH_MODE", {{"INDEPENDENT", 0}, {"MASTER", 0}, {"SYNCHRONOUS", 0}, {"MIRROR", 0}}},
    {"POWER_STATE", {{"ON", 0}, {"OFF", 0}}},
    {"POWER_STATUS", {{"ON", SCHEMA_VERSION(1, 1)}, {"OFF", SCHEMA_VERSION(1, 1)}}},
    {"PROCESS_TIME", {}},
    {"PROGRAM", {}},
    {"PROGRAM_COMMENT", {}},
    {"PROGRAM_EDIT", {{"ACTIVE", 0}, {"READY", 0}, {"NOT_READY", 0}}},
    {"PROGRAM_EDIT_NAME", {}},
    {"PROGRAM_HEADER", {}},
    {"PROGRAM_LOCATION", {}},
    {"PROGRAM_LOCATION_TYPE", {{"LOCAL", 0}, {"EXTERNAL", 0}}},
    {"PROGRAM_NEST_LEVEL", {}},
    {"ROTARY_MODE", {{"SPINDLE", 0}, {"INDEX", 0}, {"CONTOUR", 0}}},
    {"ROTARY_VELOCITY_OVERRIDE", {}},
    {"SERIAL_NUMBER", {}},
    {"SPINDLE_INTERLOCK", {{"ACTIVE", 0}, {"INACTIVE", 0}}},
    {"TOOL_ASSET_ID", {}},
    {"TOOL_GROUP", {}},
    {"TOOL_ID", {}},
    {"TOOL_NUMBER", {}},
    {"TOOL_OFFSET", {}},
    {"USER", {}},
    {"VARIABLE", {}},
    {"WAIT_STATE", {{"POWERING_UP", 0}, {"POWERING_DOWN", 0}, {"PART_LOAD", 0}, {"PART_UNLOAD", 0}, {"TOOL_LOAD", 0}, {"TOOL_UNLOAD", 0}, {"MATERIAL_LOAD", 0}, {"MATERIAL_UNLOAD", 0}, {"SECONDARY_PROCESS", 0}, {"PAUSING", 0}, {"RESUMING", 0}}},
    {"WIRE", {}},
    {"WORKHOLDING_ID", {}},
    {"WORK_OFFSET", {}},
    {"OPERATING_SYSTEM", {}},
    {"FIRMWARE", {}},
    {"APPLICATION", {}},
    {"LIBRARY", {}},
    {"HARDWARE", {}},
    {"NETWORK", {}},
    {"ROTATION", {}},
    {"TRANSLATION", {}},
    {"PROCESS_KIND_ID", {}},
    {"PART_STATUS", {{"PASS", 0}, {"FAIL", 0}}},
    {"ALARM_LIMIT", {}},
    {"PROCESS_AGGREGATE_ID", {}},
    {"PART_KIND_ID", {}},
    {"ADAPTER_URI", {}},
    {"DEVICE_REMOVED", {}},
    {"DEVICE_CHANGED", {}},
    {"SPECIFICATION_LIMIT", {}},
    {"CONNECTION_STATUS", {{"CLOSED", 0}, {"LISTEN", 0}, {"ESTABLISHED", 0}}},
    {"ADAPTER_SOFTWARE_VERSION", {}},
    {"SENSOR_ATTACHMENT", {}},
    {"CONTROL_LIMIT", {}},
    {"DEVICE_ADDED", {}},
    {"MTCONNECT_VERSION", {}},
    {"PROCESS_OCCURRENCE_ID", {}},
    {"PART_GROUP_ID", {}},
    {"PART_UNIQUE_ID", {}},
    {"ACTIVATION_COUNT", {}},
    {"DEACTIVATION_COUNT", {}},
    {"TRANSFER_COUNT", {}},
    {"LOAD_COUNT", {}},
    {"PART_PROCESSING_STATE", {{"NEEDS_PROCESSING", 0}, {"IN_PROCESS", 0}, {"PROCESSING_ENDED", 0}, {"PROCESSING_ENDED_COMPLETE", 0}, {"PROCESSING_ENDED_STOPPED", 0}, {"PROCESSING_ENDED_ABORTED", 0}, {"PROCESSING_ENDED_LOST", 0}, {"PROCESSING_ENDED_SKIPPED", 0}, {"PROCESSING_ENDED_REJECTED", 0}, {"WAITING_FOR_TRANSIT", 0}, {"IN_TRANSIT", 0}, {"TRANSIT_COMPLETE", 0}}},
    {"PROCESS_STATE", {{"INITIALIZING", 0}, {"READY", 0}, {"ACTIVE", 0}, {"COMPLETE", 0}, {"INTERRUPTED", 0}, {"ABORTED", 0}}},
    {"VALVE_STATE", {{"OPEN", 0}, {"OPENING", 0}, {"CLOSED", 0}, {"CLOSING", 0}}},
    {"LOCK_STATE", {{"LOCKED", 0}, {"UNLOCKED", 0}}},
    {"UNLOAD_COUNT", {}},
    {"CYCLE_COUNT", {}},
    {"OPERATING_MODE", {{"AUTOMATIC", 0}, {"MANUAL", 0}, {"SEMI_AUTOMATIC", 0}}},
    {"ASSET_COUNT", {}},
    {"MAINTENANCE_LIST", {}},
    {"FIXTURE_ID", {}},
    {"PART_COUNT_TYPE", {{"EACH", 0}, {"BATCH", 0}}},
    {"CLOCK_TIME", {}},
    {"NETWORK_PORT", {}},
    {"HOST_NAME", {}},
    {"LEAK_DETECT", {{"DETECTED", 0}, {"NOT_DETECTED", 0}}},
    {"BATTERY_STATE", {{"CHARGED", 0}, {"CHARGING", 0}, {"DISCHARGING", 0}, {"DISCHARGED", 0}}},
    {"FEATURE_PERSISTENT_ID", {}},
    {"SENSOR_STATE", {}},
    {"COMPONENT_DATA", {}},
    {"WORK_OFFSETS", {}},
    {"TOOL_OFFSETS", {}},
    {"FEATURE_MEASUREMENT", {}},
    {"ADAPTER_URI", {}},
    {"MEASUREMENT_TYPE", {}},
    {"MEASUREMENT_VALUE", {}},
    {"MEASUREMENT_UNITS", {}},
    {"ADAPTER_URI", {{"PASS", 0}, {"FAIL", 0}, {"REWORK", 0}, {"SYSTEM_ERROR", 0}, {"INDETERMINATE", 0}, {"NOT_ANALYZED", 0}, {"BASIC_OR_THEORETIC_EXACT_DIMENSION", 0}, {"UNDEFINED", 0}}},
    {"UNCERTAINTY_TYPE", {{"COMBINED", 0}, {"MEAN", 0}}},
    {"UNCERTAINTY", {}},
    {"ALARM_LIMIT", {}},
    {"CONTROL_LIMIT", {}},
    {"SPECIFICATION_LIMIT", {}},
    {"TOOL_CUTTING_ITEM", {}},
    {"LOCATION_ADDRESS", {}},
    {"ACTIVE_POWER_SOURCE", {}},
    {"LOCATION_NARRATIVE", {}},
    {"THICKNESS", {}},
    {"LOCATION_SPATIAL_GEOGRAPHIC", {}}
  };
