//
// Copyright 2009-2026, AMT – The Association For Manufacturing Technology (“AMT”)
// All rights reserved.
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.
//

#include <filesystem>
#include <functional>
#include <string_view>

#include "mtconnect/asset/asset.hpp"
#include "mtconnect/config.hpp"
#include "mtconnect/printer/printer.hpp"
#include "mtconnect/sink/rest_sink/cached_file.hpp"
#include "mtconnect/utilities.hpp"

namespace mtconnect::printer {
  /// @brief Printer to generate JSON Documents
  class AGENT_LIB_API HtmlPrinter : public Printer
  {
  public:
    using FileResolver = std::function<std::optional<std::filesystem::path>(const std::string&)>;

    HtmlPrinter(const std::string& browserView, Printer* delegate, bool pretty = false,
                bool validation = false)
      : Printer(pretty, validation), m_delegate(delegate), m_browserView(browserView)
    {}
    ~HtmlPrinter() override = default;

    std::string printErrors(
        const uint64_t instanceId, const unsigned int bufferSize, const uint64_t nextSeq,
        const entity::EntityList& list, bool pretty = false,
        const std::optional<std::string> requestId = std::nullopt) const override;

    std::string printProbe(
        const uint64_t instanceId, const unsigned int bufferSize, const uint64_t nextSeq,
        const unsigned int assetBufferSize, const unsigned int assetCount,
        const std::list<DevicePtr>& devices, const std::map<std::string, size_t>* count = nullptr,
        bool includeHidden = false, bool pretty = false,
        const std::optional<std::string> requestId = std::nullopt) const override;

    std::string printSample(
        const uint64_t instanceId, const unsigned int bufferSize, const uint64_t nextSeq,
        const uint64_t firstSeq, const uint64_t lastSeq, observation::ObservationList& results,
        bool pretty = false,
        const std::optional<std::string> requestId = std::nullopt) const override;
    std::string printAssets(
        const uint64_t anInstanceId, const unsigned int bufferSize, const unsigned int assetCount,
        const asset::AssetList& asset, bool pretty = false,
        const std::optional<std::string> requestId = std::nullopt) const override;
    std::string mimeType() const override { return "text/html"; }

    /// @brief Sets the function to resolve the file name to the cached file and eagerly loads
    ///        the browser view so no lazy initialization occurs while serving requests.
    /// @note Must be called during REST service initialization, before requests are handled.
    /// @param in function to be called to resolve the file name.
    void resolveBrowserView(FileResolver&& resolver) { loadFile(std::move(resolver)); }

    /// @brief Inject the content into the browser view at the placeholder.
    /// @param content the document generated by the delegate printer
    /// @return the html document, or the content if the browser view is not available
    std::string formatResult(const std::string& content) const;

  protected:
    /// @brief Resolve the browser view and split it around the content placeholder.
    /// @param in resolver Function to resolve the BrowserView to a path
    void loadFile(FileResolver&& resolver);

  protected:
    static constexpr std::string_view ContentPlaceholder {"@MTCONNECT_CONTENT@"};

    Printer* m_delegate {nullptr};
    std::string m_browserView;

    // The browser view split around the content placeholder, loaded once in loadFile()
    std::string m_prefix;
    std::string m_suffix;
    bool m_loaded {false};
  };
}  // namespace mtconnect::printer
